/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_motoros/srv/QueryIO.srv
 *
 */


#ifndef CLOPEMA_MOTOROS_MESSAGE_QUERYIOREQUEST_H
#define CLOPEMA_MOTOROS_MESSAGE_QUERYIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clopema_motoros
{
template <class ContainerAllocator>
struct QueryIORequest_
{
  typedef QueryIORequest_<ContainerAllocator> Type;

  QueryIORequest_()
    : addresses()
    , values()  {
    }
  QueryIORequest_(const ContainerAllocator& _alloc)
    : addresses(_alloc)
    , values(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _addresses_type;
  _addresses_type addresses;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::clopema_motoros::QueryIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clopema_motoros::QueryIORequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct QueryIORequest_

typedef ::clopema_motoros::QueryIORequest_<std::allocator<void> > QueryIORequest;

typedef boost::shared_ptr< ::clopema_motoros::QueryIORequest > QueryIORequestPtr;
typedef boost::shared_ptr< ::clopema_motoros::QueryIORequest const> QueryIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clopema_motoros::QueryIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clopema_motoros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/hydro/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clopema_motoros::QueryIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_motoros::QueryIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_motoros::QueryIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eaed6797153d23e63deabd000a96c03";
  }

  static const char* value(const ::clopema_motoros::QueryIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eaed6797153d23eULL;
  static const uint64_t static_value2 = 0x63deabd000a96c03ULL;
};

template<class ContainerAllocator>
struct DataType< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clopema_motoros/QueryIORequest";
  }

  static const char* value(const ::clopema_motoros::QueryIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] addresses\n\
int32[] values\n\
\n\
";
  }

  static const char* value(const ::clopema_motoros::QueryIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.addresses);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct QueryIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clopema_motoros::QueryIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clopema_motoros::QueryIORequest_<ContainerAllocator>& v)
  {
    s << indent << "addresses[]" << std::endl;
    for (size_t i = 0; i < v.addresses.size(); ++i)
    {
      s << indent << "  addresses[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.addresses[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOPEMA_MOTOROS_MESSAGE_QUERYIOREQUEST_H
