/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_motoros/srv/ReadIO.srv
 *
 */


#ifndef CLOPEMA_MOTOROS_MESSAGE_READIO_H
#define CLOPEMA_MOTOROS_MESSAGE_READIO_H

#include <ros/service_traits.h>


#include <clopema_motoros/ReadIORequest.h>
#include <clopema_motoros/ReadIOResponse.h>


namespace clopema_motoros
{

struct ReadIO
{

typedef ReadIORequest Request;
typedef ReadIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadIO
} // namespace clopema_motoros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clopema_motoros::ReadIO > {
  static const char* value()
  {
    return "8ca32b407719795f97cff837dc061ace";
  }

  static const char* value(const ::clopema_motoros::ReadIO&) { return value(); }
};

template<>
struct DataType< ::clopema_motoros::ReadIO > {
  static const char* value()
  {
    return "clopema_motoros/ReadIO";
  }

  static const char* value(const ::clopema_motoros::ReadIO&) { return value(); }
};


// service_traits::MD5Sum< ::clopema_motoros::ReadIORequest> should match 
// service_traits::MD5Sum< ::clopema_motoros::ReadIO > 
template<>
struct MD5Sum< ::clopema_motoros::ReadIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::clopema_motoros::ReadIO >::value();
  }
  static const char* value(const ::clopema_motoros::ReadIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clopema_motoros::ReadIORequest> should match 
// service_traits::DataType< ::clopema_motoros::ReadIO > 
template<>
struct DataType< ::clopema_motoros::ReadIORequest>
{
  static const char* value()
  {
    return DataType< ::clopema_motoros::ReadIO >::value();
  }
  static const char* value(const ::clopema_motoros::ReadIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clopema_motoros::ReadIOResponse> should match 
// service_traits::MD5Sum< ::clopema_motoros::ReadIO > 
template<>
struct MD5Sum< ::clopema_motoros::ReadIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clopema_motoros::ReadIO >::value();
  }
  static const char* value(const ::clopema_motoros::ReadIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clopema_motoros::ReadIOResponse> should match 
// service_traits::DataType< ::clopema_motoros::ReadIO > 
template<>
struct DataType< ::clopema_motoros::ReadIOResponse>
{
  static const char* value()
  {
    return DataType< ::clopema_motoros::ReadIO >::value();
  }
  static const char* value(const ::clopema_motoros::ReadIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOPEMA_MOTOROS_MESSAGE_READIO_H
