/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_motoros/srv/WriteIO.srv
 *
 */


#ifndef CLOPEMA_MOTOROS_MESSAGE_WRITEIO_H
#define CLOPEMA_MOTOROS_MESSAGE_WRITEIO_H

#include <ros/service_traits.h>


#include <clopema_motoros/WriteIORequest.h>
#include <clopema_motoros/WriteIOResponse.h>


namespace clopema_motoros
{

struct WriteIO
{

typedef WriteIORequest Request;
typedef WriteIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteIO
} // namespace clopema_motoros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clopema_motoros::WriteIO > {
  static const char* value()
  {
    return "266023fbe399409701b7b6672202ebcc";
  }

  static const char* value(const ::clopema_motoros::WriteIO&) { return value(); }
};

template<>
struct DataType< ::clopema_motoros::WriteIO > {
  static const char* value()
  {
    return "clopema_motoros/WriteIO";
  }

  static const char* value(const ::clopema_motoros::WriteIO&) { return value(); }
};


// service_traits::MD5Sum< ::clopema_motoros::WriteIORequest> should match 
// service_traits::MD5Sum< ::clopema_motoros::WriteIO > 
template<>
struct MD5Sum< ::clopema_motoros::WriteIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::clopema_motoros::WriteIO >::value();
  }
  static const char* value(const ::clopema_motoros::WriteIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clopema_motoros::WriteIORequest> should match 
// service_traits::DataType< ::clopema_motoros::WriteIO > 
template<>
struct DataType< ::clopema_motoros::WriteIORequest>
{
  static const char* value()
  {
    return DataType< ::clopema_motoros::WriteIO >::value();
  }
  static const char* value(const ::clopema_motoros::WriteIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clopema_motoros::WriteIOResponse> should match 
// service_traits::MD5Sum< ::clopema_motoros::WriteIO > 
template<>
struct MD5Sum< ::clopema_motoros::WriteIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clopema_motoros::WriteIO >::value();
  }
  static const char* value(const ::clopema_motoros::WriteIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clopema_motoros::WriteIOResponse> should match 
// service_traits::DataType< ::clopema_motoros::WriteIO > 
template<>
struct DataType< ::clopema_motoros::WriteIOResponse>
{
  static const char* value()
  {
    return DataType< ::clopema_motoros::WriteIO >::value();
  }
  static const char* value(const ::clopema_motoros::WriteIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOPEMA_MOTOROS_MESSAGE_WRITEIO_H
