/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/clopema_measurements/msg/MeasureDataDefinition.msg
 *
 */


#ifndef CLOPEMA_MEASUREMENTS_MESSAGE_MEASUREDATADEFINITION_H
#define CLOPEMA_MEASUREMENTS_MESSAGE_MEASUREDATADEFINITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>
#include <sensor_msgs/JointState.h>

namespace clopema_measurements
{
template <class ContainerAllocator>
struct MeasureDataDefinition_
{
  typedef MeasureDataDefinition_<ContainerAllocator> Type;

  MeasureDataDefinition_()
    : trajectories()
    , measure_after()
    , wait_after()
    , start_state()
    , robot_speed()
    , special_action()  {
    }
  MeasureDataDefinition_(const ContainerAllocator& _alloc)
    : trajectories(_alloc)
    , measure_after(_alloc)
    , wait_after(_alloc)
    , start_state(_alloc)
    , robot_speed(_alloc)
    , special_action(_alloc)  {
    }



   typedef std::vector< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::other >  _trajectories_type;
  _trajectories_type trajectories;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _measure_after_type;
  _measure_after_type measure_after;

   typedef std::vector<ros::Duration, typename ContainerAllocator::template rebind<ros::Duration>::other >  _wait_after_type;
  _wait_after_type wait_after;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _start_state_type;
  _start_state_type start_state;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _robot_speed_type;
  _robot_speed_type robot_speed;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _special_action_type;
  _special_action_type special_action;




  typedef boost::shared_ptr< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MeasureDataDefinition_

typedef ::clopema_measurements::MeasureDataDefinition_<std::allocator<void> > MeasureDataDefinition;

typedef boost::shared_ptr< ::clopema_measurements::MeasureDataDefinition > MeasureDataDefinitionPtr;
typedef boost::shared_ptr< ::clopema_measurements::MeasureDataDefinition const> MeasureDataDefinitionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clopema_measurements

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'clopema_measurements': ['/home/andrew/TeamProject/Clopema/src/clopema_cvut/clopema_measurements/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a63794819c27a604e27ffee6fc9e954";
  }

  static const char* value(const ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a63794819c27a60ULL;
  static const uint64_t static_value2 = 0x4e27ffee6fc9e954ULL;
};

template<class ContainerAllocator>
struct DataType< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clopema_measurements/MeasureDataDefinition";
  }

  static const char* value(const ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory[] trajectories\n\
bool[] measure_after\n\
duration[] wait_after\n\
\n\
sensor_msgs/JointState start_state\n\
\n\
#Optional\n\
float64[] robot_speed\n\
\n\
#Optional\n\
#0 - nothing, 1 - call reset mars service\n\
int32[] special_action\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
";
  }

  static const char* value(const ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectories);
      stream.next(m.measure_after);
      stream.next(m.wait_after);
      stream.next(m.start_state);
      stream.next(m.robot_speed);
      stream.next(m.special_action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MeasureDataDefinition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clopema_measurements::MeasureDataDefinition_<ContainerAllocator>& v)
  {
    s << indent << "trajectories[]" << std::endl;
    for (size_t i = 0; i < v.trajectories.size(); ++i)
    {
      s << indent << "  trajectories[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectories[i]);
    }
    s << indent << "measure_after[]" << std::endl;
    for (size_t i = 0; i < v.measure_after.size(); ++i)
    {
      s << indent << "  measure_after[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.measure_after[i]);
    }
    s << indent << "wait_after[]" << std::endl;
    for (size_t i = 0; i < v.wait_after.size(); ++i)
    {
      s << indent << "  wait_after[" << i << "]: ";
      Printer<ros::Duration>::stream(s, indent + "  ", v.wait_after[i]);
    }
    s << indent << "start_state: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.start_state);
    s << indent << "robot_speed[]" << std::endl;
    for (size_t i = 0; i < v.robot_speed.size(); ++i)
    {
      s << indent << "  robot_speed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.robot_speed[i]);
    }
    s << indent << "special_action[]" << std::endl;
    for (size_t i = 0; i < v.special_action.size(); ++i)
    {
      s << indent << "  special_action[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.special_action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOPEMA_MEASUREMENTS_MESSAGE_MEASUREDATADEFINITION_H
