/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_testbed/clopema_moveit/srv/ClopemaGraspFromTable.srv
 *
 */


#ifndef CLOPEMA_MOVEIT_MESSAGE_CLOPEMAGRASPFROMTABLEREQUEST_H
#define CLOPEMA_MOVEIT_MESSAGE_CLOPEMAGRASPFROMTABLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace clopema_moveit
{
template <class ContainerAllocator>
struct ClopemaGraspFromTableRequest_
{
  typedef ClopemaGraspFromTableRequest_<ContainerAllocator> Type;

  ClopemaGraspFromTableRequest_()
    : frame_id()
    , ik_link()
    , table_desk()
    , poses()
    , offset_minus(0.0)
    , offset_plus(0.0)
    , offset_table_minus(0.0)
    , offset_table_plus(0.0)
    , grasping_angle(0.0)
    , final_poses()  {
    }
  ClopemaGraspFromTableRequest_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , ik_link(_alloc)
    , table_desk(_alloc)
    , poses(_alloc)
    , offset_minus(0.0)
    , offset_plus(0.0)
    , offset_table_minus(0.0)
    , offset_table_plus(0.0)
    , grasping_angle(0.0)
    , final_poses(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ik_link_type;
  _ik_link_type ik_link;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_desk_type;
  _table_desk_type table_desk;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef double _offset_minus_type;
  _offset_minus_type offset_minus;

   typedef double _offset_plus_type;
  _offset_plus_type offset_plus;

   typedef double _offset_table_minus_type;
  _offset_table_minus_type offset_table_minus;

   typedef double _offset_table_plus_type;
  _offset_table_plus_type offset_table_plus;

   typedef double _grasping_angle_type;
  _grasping_angle_type grasping_angle;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _final_poses_type;
  _final_poses_type final_poses;




  typedef boost::shared_ptr< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ClopemaGraspFromTableRequest_

typedef ::clopema_moveit::ClopemaGraspFromTableRequest_<std::allocator<void> > ClopemaGraspFromTableRequest;

typedef boost::shared_ptr< ::clopema_moveit::ClopemaGraspFromTableRequest > ClopemaGraspFromTableRequestPtr;
typedef boost::shared_ptr< ::clopema_moveit::ClopemaGraspFromTableRequest const> ClopemaGraspFromTableRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clopema_moveit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/hydro/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/hydro/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/hydro/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/hydro/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5da89094f5f39ca3abc4f72efb19ca97";
  }

  static const char* value(const ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5da89094f5f39ca3ULL;
  static const uint64_t static_value2 = 0xabc4f72efb19ca97ULL;
};

template<class ContainerAllocator>
struct DataType< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clopema_moveit/ClopemaGraspFromTableRequest";
  }

  static const char* value(const ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string frame_id\n\
\n\
\n\
string ik_link\n\
\n\
\n\
\n\
string table_desk\n\
\n\
\n\
\n\
geometry_msgs/Pose[] poses\n\
\n\
\n\
\n\
float64 offset_minus\n\
float64 offset_plus\n\
\n\
\n\
\n\
float64 offset_table_minus\n\
float64 offset_table_plus\n\
\n\
\n\
float64 grasping_angle\n\
\n\
\n\
geometry_msgs/Pose[] final_poses\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.ik_link);
      stream.next(m.table_desk);
      stream.next(m.poses);
      stream.next(m.offset_minus);
      stream.next(m.offset_plus);
      stream.next(m.offset_table_minus);
      stream.next(m.offset_table_plus);
      stream.next(m.grasping_angle);
      stream.next(m.final_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ClopemaGraspFromTableRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clopema_moveit::ClopemaGraspFromTableRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "ik_link: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ik_link);
    s << indent << "table_desk: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_desk);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "offset_minus: ";
    Printer<double>::stream(s, indent + "  ", v.offset_minus);
    s << indent << "offset_plus: ";
    Printer<double>::stream(s, indent + "  ", v.offset_plus);
    s << indent << "offset_table_minus: ";
    Printer<double>::stream(s, indent + "  ", v.offset_table_minus);
    s << indent << "offset_table_plus: ";
    Printer<double>::stream(s, indent + "  ", v.offset_table_plus);
    s << indent << "grasping_angle: ";
    Printer<double>::stream(s, indent + "  ", v.grasping_angle);
    s << indent << "final_poses[]" << std::endl;
    for (size_t i = 0; i < v.final_poses.size(); ++i)
    {
      s << indent << "  final_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.final_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOPEMA_MOVEIT_MESSAGE_CLOPEMAGRASPFROMTABLEREQUEST_H
