/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_testbed/clopema_moveit/srv/ClopemaLinearInterpolationDual.srv
 *
 */


#ifndef CLOPEMA_MOVEIT_MESSAGE_CLOPEMALINEARINTERPOLATIONDUALREQUEST_H
#define CLOPEMA_MOVEIT_MESSAGE_CLOPEMALINEARINTERPOLATIONDUALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace clopema_moveit
{
template <class ContainerAllocator>
struct ClopemaLinearInterpolationDualRequest_
{
  typedef ClopemaLinearInterpolationDualRequest_<ContainerAllocator> Type;

  ClopemaLinearInterpolationDualRequest_()
    : header()
    , ik_link_name_1()
    , ik_link_name_2()
    , poses_1()
    , poses_2()  {
    }
  ClopemaLinearInterpolationDualRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ik_link_name_1(_alloc)
    , ik_link_name_2(_alloc)
    , poses_1(_alloc)
    , poses_2(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ik_link_name_1_type;
  _ik_link_name_1_type ik_link_name_1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ik_link_name_2_type;
  _ik_link_name_2_type ik_link_name_2;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_1_type;
  _poses_1_type poses_1;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_2_type;
  _poses_2_type poses_2;




  typedef boost::shared_ptr< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ClopemaLinearInterpolationDualRequest_

typedef ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<std::allocator<void> > ClopemaLinearInterpolationDualRequest;

typedef boost::shared_ptr< ::clopema_moveit::ClopemaLinearInterpolationDualRequest > ClopemaLinearInterpolationDualRequestPtr;
typedef boost::shared_ptr< ::clopema_moveit::ClopemaLinearInterpolationDualRequest const> ClopemaLinearInterpolationDualRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clopema_moveit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'shape_msgs': ['/opt/ros/hydro/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/hydro/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/hydro/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/hydro/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "930015b0a4c55fb8011e706873f22b36";
  }

  static const char* value(const ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x930015b0a4c55fb8ULL;
  static const uint64_t static_value2 = 0x011e706873f22b36ULL;
};

template<class ContainerAllocator>
struct DataType< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clopema_moveit/ClopemaLinearInterpolationDualRequest";
  }

  static const char* value(const ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string ik_link_name_1\n\
string ik_link_name_2\n\
geometry_msgs/Pose[] poses_1\n\
geometry_msgs/Pose[] poses_2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ik_link_name_1);
      stream.next(m.ik_link_name_2);
      stream.next(m.poses_1);
      stream.next(m.poses_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ClopemaLinearInterpolationDualRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clopema_moveit::ClopemaLinearInterpolationDualRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ik_link_name_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ik_link_name_1);
    s << indent << "ik_link_name_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ik_link_name_2);
    s << indent << "poses_1[]" << std::endl;
    for (size_t i = 0; i < v.poses_1.size(); ++i)
    {
      s << indent << "  poses_1[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses_1[i]);
    }
    s << indent << "poses_2[]" << std::endl;
    for (size_t i = 0; i < v.poses_2.size(); ++i)
    {
      s << indent << "  poses_2[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses_2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOPEMA_MOVEIT_MESSAGE_CLOPEMALINEARINTERPOLATIONDUALREQUEST_H
