"""autogenerated by genpy from toradex/ToradexShutter.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ToradexShutter(genpy.Message):
  _md5sum = "b2b8b0b135c6438552dcd4250ce03ab4"
  _type = "toradex/ToradexShutter"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool shutter1
bool shutter2
bool shutter3

"""
  __slots__ = ['shutter1','shutter2','shutter3']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       shutter1,shutter2,shutter3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ToradexShutter, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.shutter1 is None:
        self.shutter1 = False
      if self.shutter2 is None:
        self.shutter2 = False
      if self.shutter3 is None:
        self.shutter3 = False
    else:
      self.shutter1 = False
      self.shutter2 = False
      self.shutter3 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.shutter1, _x.shutter2, _x.shutter3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.shutter1, _x.shutter2, _x.shutter3,) = _struct_3B.unpack(str[start:end])
      self.shutter1 = bool(self.shutter1)
      self.shutter2 = bool(self.shutter2)
      self.shutter3 = bool(self.shutter3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.shutter1, _x.shutter2, _x.shutter3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.shutter1, _x.shutter2, _x.shutter3,) = _struct_3B.unpack(str[start:end])
      self.shutter1 = bool(self.shutter1)
      self.shutter2 = bool(self.shutter2)
      self.shutter3 = bool(self.shutter3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
