/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/pikron_mars/msg/MarsState.msg
 *
 */


#ifndef PIKRON_MARS_MESSAGE_MARSSTATE_H
#define PIKRON_MARS_MESSAGE_MARSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pikron_mars
{
template <class ContainerAllocator>
struct MarsState_
{
  typedef MarsState_<ContainerAllocator> Type;

  MarsState_()
    : A(0.0)
    , B(0.0)
    , C(0.0)  {
    }
  MarsState_(const ContainerAllocator& _alloc)
    : A(0.0)
    , B(0.0)
    , C(0.0)  {
    }



   typedef double _A_type;
  _A_type A;

   typedef double _B_type;
  _B_type B;

   typedef double _C_type;
  _C_type C;




  typedef boost::shared_ptr< ::pikron_mars::MarsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pikron_mars::MarsState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MarsState_

typedef ::pikron_mars::MarsState_<std::allocator<void> > MarsState;

typedef boost::shared_ptr< ::pikron_mars::MarsState > MarsStatePtr;
typedef boost::shared_ptr< ::pikron_mars::MarsState const> MarsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pikron_mars::MarsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pikron_mars::MarsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pikron_mars

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pikron_mars': ['/home/andrew/TeamProject/Clopema/src/clopema_cvut/pikron_mars/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pikron_mars::MarsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pikron_mars::MarsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pikron_mars::MarsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pikron_mars::MarsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pikron_mars::MarsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pikron_mars::MarsState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pikron_mars::MarsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0cba5640df8792c44a7758578fc35bc";
  }

  static const char* value(const ::pikron_mars::MarsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0cba5640df8792cULL;
  static const uint64_t static_value2 = 0x44a7758578fc35bcULL;
};

template<class ContainerAllocator>
struct DataType< ::pikron_mars::MarsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pikron_mars/MarsState";
  }

  static const char* value(const ::pikron_mars::MarsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pikron_mars::MarsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 A\n\
float64 B\n\
float64 C\n\
\n\
";
  }

  static const char* value(const ::pikron_mars::MarsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pikron_mars::MarsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MarsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pikron_mars::MarsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pikron_mars::MarsState_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<double>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<double>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<double>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKRON_MARS_MESSAGE_MARSSTATE_H
