/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_testbed/clopema_smach/msg/MA1400JointState.msg
 *
 */


#ifndef CLOPEMA_SMACH_MESSAGE_MA1400JOINTSTATE_H
#define CLOPEMA_SMACH_MESSAGE_MA1400JOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clopema_smach
{
template <class ContainerAllocator>
struct MA1400JointState_
{
  typedef MA1400JointState_<ContainerAllocator> Type;

  MA1400JointState_()
    : s(0.0)
    , l(0.0)
    , u(0.0)
    , r(0.0)
    , b(0.0)
    , t(0.0)  {
    }
  MA1400JointState_(const ContainerAllocator& _alloc)
    : s(0.0)
    , l(0.0)
    , u(0.0)
    , r(0.0)
    , b(0.0)
    , t(0.0)  {
    }



   typedef double _s_type;
  _s_type s;

   typedef double _l_type;
  _l_type l;

   typedef double _u_type;
  _u_type u;

   typedef double _r_type;
  _r_type r;

   typedef double _b_type;
  _b_type b;

   typedef double _t_type;
  _t_type t;




  typedef boost::shared_ptr< ::clopema_smach::MA1400JointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clopema_smach::MA1400JointState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MA1400JointState_

typedef ::clopema_smach::MA1400JointState_<std::allocator<void> > MA1400JointState;

typedef boost::shared_ptr< ::clopema_smach::MA1400JointState > MA1400JointStatePtr;
typedef boost::shared_ptr< ::clopema_smach::MA1400JointState const> MA1400JointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clopema_smach::MA1400JointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clopema_smach::MA1400JointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clopema_smach

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'clopema_smach': ['/home/andrew/TeamProject/Clopema/src/clopema_testbed/clopema_smach/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clopema_smach::MA1400JointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clopema_smach::MA1400JointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clopema_smach::MA1400JointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3b3791f114f3a61c72e1b1a7e520805";
  }

  static const char* value(const ::clopema_smach::MA1400JointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3b3791f114f3a61ULL;
  static const uint64_t static_value2 = 0xc72e1b1a7e520805ULL;
};

template<class ContainerAllocator>
struct DataType< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clopema_smach/MA1400JointState";
  }

  static const char* value(const ::clopema_smach::MA1400JointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 s\n\
float64 l\n\
float64 u\n\
float64 r\n\
float64 b\n\
float64 t\n\
\n\
";
  }

  static const char* value(const ::clopema_smach::MA1400JointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.l);
      stream.next(m.u);
      stream.next(m.r);
      stream.next(m.b);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MA1400JointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clopema_smach::MA1400JointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clopema_smach::MA1400JointState_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "l: ";
    Printer<double>::stream(s, indent + "  ", v.l);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOPEMA_SMACH_MESSAGE_MA1400JOINTSTATE_H
