/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/srv/ToradexSetShutter.srv
 *
 */


#ifndef TORADEX_MESSAGE_TORADEXSETSHUTTER_H
#define TORADEX_MESSAGE_TORADEXSETSHUTTER_H

#include <ros/service_traits.h>


#include <toradex/ToradexSetShutterRequest.h>
#include <toradex/ToradexSetShutterResponse.h>


namespace toradex
{

struct ToradexSetShutter
{

typedef ToradexSetShutterRequest Request;
typedef ToradexSetShutterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToradexSetShutter
} // namespace toradex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::toradex::ToradexSetShutter > {
  static const char* value()
  {
    return "890c63bccb9f8d0b9c94f356912df66f";
  }

  static const char* value(const ::toradex::ToradexSetShutter&) { return value(); }
};

template<>
struct DataType< ::toradex::ToradexSetShutter > {
  static const char* value()
  {
    return "toradex/ToradexSetShutter";
  }

  static const char* value(const ::toradex::ToradexSetShutter&) { return value(); }
};


// service_traits::MD5Sum< ::toradex::ToradexSetShutterRequest> should match 
// service_traits::MD5Sum< ::toradex::ToradexSetShutter > 
template<>
struct MD5Sum< ::toradex::ToradexSetShutterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::toradex::ToradexSetShutter >::value();
  }
  static const char* value(const ::toradex::ToradexSetShutterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::toradex::ToradexSetShutterRequest> should match 
// service_traits::DataType< ::toradex::ToradexSetShutter > 
template<>
struct DataType< ::toradex::ToradexSetShutterRequest>
{
  static const char* value()
  {
    return DataType< ::toradex::ToradexSetShutter >::value();
  }
  static const char* value(const ::toradex::ToradexSetShutterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::toradex::ToradexSetShutterResponse> should match 
// service_traits::MD5Sum< ::toradex::ToradexSetShutter > 
template<>
struct MD5Sum< ::toradex::ToradexSetShutterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::toradex::ToradexSetShutter >::value();
  }
  static const char* value(const ::toradex::ToradexSetShutterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::toradex::ToradexSetShutterResponse> should match 
// service_traits::DataType< ::toradex::ToradexSetShutter > 
template<>
struct DataType< ::toradex::ToradexSetShutterResponse>
{
  static const char* value()
  {
    return DataType< ::toradex::ToradexSetShutter >::value();
  }
  static const char* value(const ::toradex::ToradexSetShutterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TORADEX_MESSAGE_TORADEXSETSHUTTER_H
