/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/msg/ToradexShutter.msg
 *
 */


#ifndef TORADEX_MESSAGE_TORADEXSHUTTER_H
#define TORADEX_MESSAGE_TORADEXSHUTTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace toradex
{
template <class ContainerAllocator>
struct ToradexShutter_
{
  typedef ToradexShutter_<ContainerAllocator> Type;

  ToradexShutter_()
    : shutter1(false)
    , shutter2(false)
    , shutter3(false)  {
    }
  ToradexShutter_(const ContainerAllocator& _alloc)
    : shutter1(false)
    , shutter2(false)
    , shutter3(false)  {
    }



   typedef uint8_t _shutter1_type;
  _shutter1_type shutter1;

   typedef uint8_t _shutter2_type;
  _shutter2_type shutter2;

   typedef uint8_t _shutter3_type;
  _shutter3_type shutter3;




  typedef boost::shared_ptr< ::toradex::ToradexShutter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::toradex::ToradexShutter_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ToradexShutter_

typedef ::toradex::ToradexShutter_<std::allocator<void> > ToradexShutter;

typedef boost::shared_ptr< ::toradex::ToradexShutter > ToradexShutterPtr;
typedef boost::shared_ptr< ::toradex::ToradexShutter const> ToradexShutterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::toradex::ToradexShutter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::toradex::ToradexShutter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace toradex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'toradex': ['/home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexShutter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexShutter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexShutter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexShutter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexShutter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexShutter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::toradex::ToradexShutter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2b8b0b135c6438552dcd4250ce03ab4";
  }

  static const char* value(const ::toradex::ToradexShutter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2b8b0b135c64385ULL;
  static const uint64_t static_value2 = 0x52dcd4250ce03ab4ULL;
};

template<class ContainerAllocator>
struct DataType< ::toradex::ToradexShutter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "toradex/ToradexShutter";
  }

  static const char* value(const ::toradex::ToradexShutter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::toradex::ToradexShutter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool shutter1\n\
bool shutter2\n\
bool shutter3\n\
\n\
";
  }

  static const char* value(const ::toradex::ToradexShutter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::toradex::ToradexShutter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shutter1);
      stream.next(m.shutter2);
      stream.next(m.shutter3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ToradexShutter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::toradex::ToradexShutter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::toradex::ToradexShutter_<ContainerAllocator>& v)
  {
    s << indent << "shutter1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shutter1);
    s << indent << "shutter2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shutter2);
    s << indent << "shutter3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shutter3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORADEX_MESSAGE_TORADEXSHUTTER_H
