/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/msg/ToradexState.msg
 *
 */


#ifndef TORADEX_MESSAGE_TORADEXSTATE_H
#define TORADEX_MESSAGE_TORADEXSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace toradex
{
template <class ContainerAllocator>
struct ToradexState_
{
  typedef ToradexState_<ContainerAllocator> Type;

  ToradexState_()
    : portA(0)
    , portB(0)
    , portC(0)  {
    }
  ToradexState_(const ContainerAllocator& _alloc)
    : portA(0)
    , portB(0)
    , portC(0)  {
    }



   typedef uint8_t _portA_type;
  _portA_type portA;

   typedef uint8_t _portB_type;
  _portB_type portB;

   typedef uint8_t _portC_type;
  _portC_type portC;




  typedef boost::shared_ptr< ::toradex::ToradexState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::toradex::ToradexState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ToradexState_

typedef ::toradex::ToradexState_<std::allocator<void> > ToradexState;

typedef boost::shared_ptr< ::toradex::ToradexState > ToradexStatePtr;
typedef boost::shared_ptr< ::toradex::ToradexState const> ToradexStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::toradex::ToradexState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::toradex::ToradexState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace toradex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'toradex': ['/home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::toradex::ToradexState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "287f5638374eef90b186ce17d95c5bcd";
  }

  static const char* value(const ::toradex::ToradexState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x287f5638374eef90ULL;
  static const uint64_t static_value2 = 0xb186ce17d95c5bcdULL;
};

template<class ContainerAllocator>
struct DataType< ::toradex::ToradexState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "toradex/ToradexState";
  }

  static const char* value(const ::toradex::ToradexState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::toradex::ToradexState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 portA\n\
uint8 portB\n\
uint8 portC\n\
\n\
";
  }

  static const char* value(const ::toradex::ToradexState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::toradex::ToradexState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.portA);
      stream.next(m.portB);
      stream.next(m.portC);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ToradexState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::toradex::ToradexState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::toradex::ToradexState_<ContainerAllocator>& v)
  {
    s << indent << "portA: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.portA);
    s << indent << "portB: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.portB);
    s << indent << "portC: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.portC);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORADEX_MESSAGE_TORADEXSTATE_H
