/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/srv/ToradexSetDirection.srv
 *
 */


#ifndef TORADEX_MESSAGE_TORADEXSETDIRECTIONREQUEST_H
#define TORADEX_MESSAGE_TORADEXSETDIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <toradex/ToradexDirection.h>

namespace toradex
{
template <class ContainerAllocator>
struct ToradexSetDirectionRequest_
{
  typedef ToradexSetDirectionRequest_<ContainerAllocator> Type;

  ToradexSetDirectionRequest_()
    : direction()  {
    }
  ToradexSetDirectionRequest_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
    }



   typedef  ::toradex::ToradexDirection_<ContainerAllocator>  _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ToradexSetDirectionRequest_

typedef ::toradex::ToradexSetDirectionRequest_<std::allocator<void> > ToradexSetDirectionRequest;

typedef boost::shared_ptr< ::toradex::ToradexSetDirectionRequest > ToradexSetDirectionRequestPtr;
typedef boost::shared_ptr< ::toradex::ToradexSetDirectionRequest const> ToradexSetDirectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace toradex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'toradex': ['/home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fead1edffddd1200f9ffc8cbb35ff44f";
  }

  static const char* value(const ::toradex::ToradexSetDirectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfead1edffddd1200ULL;
  static const uint64_t static_value2 = 0xf9ffc8cbb35ff44fULL;
};

template<class ContainerAllocator>
struct DataType< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "toradex/ToradexSetDirectionRequest";
  }

  static const char* value(const ::toradex::ToradexSetDirectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ToradexDirection direction\n\
\n\
================================================================================\n\
MSG: toradex/ToradexDirection\n\
uint8 portA\n\
uint8 portB\n\
uint8 portC\n\
\n\
";
  }

  static const char* value(const ::toradex::ToradexSetDirectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ToradexSetDirectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::toradex::ToradexSetDirectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::toradex::ToradexSetDirectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::toradex::ToradexDirection_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORADEX_MESSAGE_TORADEXSETDIRECTIONREQUEST_H
