/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/andrew/TeamProject/Clopema/src/clopema_cvut/toradex/srv/ToradexSetState.srv
 *
 */


#ifndef TORADEX_MESSAGE_TORADEXSETSTATE_H
#define TORADEX_MESSAGE_TORADEXSETSTATE_H

#include <ros/service_traits.h>


#include <toradex/ToradexSetStateRequest.h>
#include <toradex/ToradexSetStateResponse.h>


namespace toradex
{

struct ToradexSetState
{

typedef ToradexSetStateRequest Request;
typedef ToradexSetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToradexSetState
} // namespace toradex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::toradex::ToradexSetState > {
  static const char* value()
  {
    return "8055dc16963622d8825109a89e188a29";
  }

  static const char* value(const ::toradex::ToradexSetState&) { return value(); }
};

template<>
struct DataType< ::toradex::ToradexSetState > {
  static const char* value()
  {
    return "toradex/ToradexSetState";
  }

  static const char* value(const ::toradex::ToradexSetState&) { return value(); }
};


// service_traits::MD5Sum< ::toradex::ToradexSetStateRequest> should match 
// service_traits::MD5Sum< ::toradex::ToradexSetState > 
template<>
struct MD5Sum< ::toradex::ToradexSetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::toradex::ToradexSetState >::value();
  }
  static const char* value(const ::toradex::ToradexSetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::toradex::ToradexSetStateRequest> should match 
// service_traits::DataType< ::toradex::ToradexSetState > 
template<>
struct DataType< ::toradex::ToradexSetStateRequest>
{
  static const char* value()
  {
    return DataType< ::toradex::ToradexSetState >::value();
  }
  static const char* value(const ::toradex::ToradexSetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::toradex::ToradexSetStateResponse> should match 
// service_traits::MD5Sum< ::toradex::ToradexSetState > 
template<>
struct MD5Sum< ::toradex::ToradexSetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::toradex::ToradexSetState >::value();
  }
  static const char* value(const ::toradex::ToradexSetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::toradex::ToradexSetStateResponse> should match 
// service_traits::DataType< ::toradex::ToradexSetState > 
template<>
struct DataType< ::toradex::ToradexSetStateResponse>
{
  static const char* value()
  {
    return DataType< ::toradex::ToradexSetState >::value();
  }
  static const char* value(const ::toradex::ToradexSetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TORADEX_MESSAGE_TORADEXSETSTATE_H
